basePath: /
info:
  contact: {}
  description: Fatcat backend API documentation
  title: Fatcat API
  version: "1.0"
paths:
  /fetch:
    get:
      description: Fetch data from jsonplaceholder
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Fetch data from jsonplaceholder
      tags:
      - health
  /health:
    get:
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show the health status
      tags:
      - health
swagger: "2.0"
