name: auto label

on:
  pull_request:
     types: [opened, reopened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'feature/')
        with:
          labels: enhancement

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'test/')
        with:
          labels: test

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'bugfix/')
        with:
          labels: bug

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'refactor/')
        with:
          labels: refactor

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'docs/')
        with:
          labels: documentation

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.head_ref, 'sync/')
        with:
          labels: sync
